Net/ThemeName "Tokyonight-Dark-Moon"
Net/IconThemeName "Papirus-Dark"
Gtk/CursorThemeName "DMZ-White"
Net/EnableEventSounds 1
Net/EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintslight"
Xft/RGBA "rgb"
